version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0146424Minh
      - POSTGRES_DB=slm_app
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    volumes:
      - .:/slm_api
    networks:
      - slm-network

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0146424Minh
      - POSTGRES_DB=slm_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - slm-network

volumes:
  postgres_data:

networks:
  slm-network:
    driver: bridge 